import gleeunit/should
import phonetic_gleam/nysiis

pub fn codes_for_known_words_test() {
  nysiis.encode("Willis")
  |> should.equal("WALA")
  nysiis.encode("Bishop")
  |> should.equal("BASAP")
  nysiis.encode("Carlson")
  |> should.equal("CARLSAN")
  nysiis.encode("Carr")
  |> should.equal("CAR")
  nysiis.encode("Chapman")
  |> should.equal("CAPNAN")
  nysiis.encode("Franklin")
  |> should.equal("FRANCLAN")
  nysiis.encode("Greene")
  |> should.equal("GRAN")
  nysiis.encode("Harper")
  |> should.equal("HARPAR")
  nysiis.encode("Jacobs")
  |> should.equal("JACAB")
  nysiis.encode("Larson")
  |> should.equal("LARSAN")
  nysiis.encode("Lawrence")
  |> should.equal("LARANC")
  nysiis.encode("Lawson")
  |> should.equal("LASAN")
  nysiis.encode("Lawson")
  |> should.equal("LASAN")
  nysiis.encode("Louis, XVI")
  |> should.equal("LASXV")
  nysiis.encode("Lynch")
  |> should.equal("LYNC")
  nysiis.encode("Mackenzie")
  |> should.equal("MCANSY")
  nysiis.encode("Matthews")
  |> should.equal("MATA")
  nysiis.encode("McCormack")
  |> should.equal("MCARNAC")
  nysiis.encode("McDaniel")
  |> should.equal("MCDANAL")
  nysiis.encode("McDonald")
  |> should.equal("MCDANALD")
  nysiis.encode("Mclaughlin")
  |> should.equal("MCLAGLAN")
  nysiis.encode("Morrison")
  |> should.equal("MARASAN")
  nysiis.encode("O'Banion")
  |> should.equal("OBANAN")
  nysiis.encode("O'Brien")
  |> should.equal("OBRAN")
  nysiis.encode("Richards")
  |> should.equal("RACARD")
  nysiis.encode("Silva")
  |> should.equal("SALV")
  nysiis.encode("Watkins")
  |> should.equal("WATCAN")
  nysiis.encode("Wheeler")
  |> should.equal("WALAR")
  nysiis.encode("brown, sr")
  |> should.equal("BRANSR")
  nysiis.encode("browne, III")
  |> should.equal("BRAN")
  nysiis.encode("browne, IV")
  |> should.equal("BRANAV")
  nysiis.encode("knight")
  |> should.equal("NAGT")
  nysiis.encode("mitchell")
  |> should.equal("MATCAL")
  nysiis.encode("o'daniel")
  |> should.equal("ODANAL")
}
