name = "phonetic_gleam"
version = "0.1.1"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
licences = ["MIT"]
description = "A collection of gleam algorithms dealing with phonetics."
repository = { type = "github", user = "leobm", repo = "phonetic_gleam" }
links = [{ title = "Gleam", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = "~> 0.36"

[dev-dependencies]
gleeunit = "~> 1.0.2"

[javascript]
# Generate TypeScript .d.ts files
# typescript_declarations = true
